using UnityEngine;

public static class TypingInputUtility{
    public static char GetCharFromKeyCode(KeyCode keyCode) {
        return keyCode switch {
            KeyCode.A => 'a',
            KeyCode.B => 'b',
            KeyCode.C => 'c',
            KeyCode.D => 'd',
            KeyCode.E => 'e',
            KeyCode.F => 'f',
            KeyCode.G => 'g',
            KeyCode.H => 'h',
            KeyCode.I => 'i',
            KeyCode.J => 'j',
            KeyCode.K => 'k',
            KeyCode.L => 'l',
            KeyCode.M => 'm',
            KeyCode.N => 'n',
            KeyCode.O => 'o',
            KeyCode.P => 'p',
            KeyCode.Q => 'q',
            KeyCode.R => 'r',
            KeyCode.S => 's',
            KeyCode.T => 't',
            KeyCode.U => 'u',
            KeyCode.V => 'v',
            KeyCode.W => 'w',
            KeyCode.X => 'x',
            KeyCode.Y => 'y',
            KeyCode.Z => 'z',
            KeyCode.Alpha0 => '0',
            KeyCode.Alpha1 => '1',
            KeyCode.Alpha2 => '2',
            KeyCode.Alpha3 => '3',
            KeyCode.Alpha4 => '4',
            KeyCode.Alpha5 => '5',
            KeyCode.Alpha6 => '6',
            KeyCode.Alpha7 => '7',
            KeyCode.Alpha8 => '8',
            KeyCode.Alpha9 => '9',
            KeyCode.Minus => '-',
            KeyCode.Caret => '^',
            KeyCode.Backslash => '\\',
            KeyCode.At => '@',
            KeyCode.LeftBracket => '[',
            KeyCode.Semicolon => ';',
            KeyCode.Colon => ':',
            KeyCode.RightBracket => ']',
            KeyCode.Comma => ',',
            KeyCode.Period => '.',
            KeyCode.Slash => '/',
            KeyCode.Underscore => '_',
            KeyCode.Backspace => '\b',
            KeyCode.Return => '\r',
            KeyCode.Space => ' ',
            //上記以外のキーが押された場合は「null文字」を返す。
            _ => '\0',
        };
    }
}